name: Monitor MASE Plafond automatico

on:
  workflow_dispatch: # Adesso parte SOLO se viene innescato manualmente o dall'API esterna

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests

      - name: Run Sniper Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
        run: python main.py
